stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: bitnami/git:latest
  script:
    - git config --global user.name "GitLab Mirror Bot"
    - git config --global user.email "mirror@example.com"
    - git remote add github https://alrifqidarmawan:${GITHUB_TOKEN}@github.com/Fantastic-4-projects/backend-pawtner.git
    - git push github HEAD:refs/heads/$CI_COMMIT_REF_NAME
  tags:
    - github-mirror
  only:
    - branches
