variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: bitnami/git:latest
  script:
    - git remote set-url --push origin "https://alrifqidarmawan:${GITHUB_TOKEN}@github.com/Fantastic-4-projects/backend-pawtner.git"
    - git push --mirror origin
  tags:
    - github-mirror
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'